# Generated by Django 4.2.2 on 2023-07-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohorte1',
            name='CI',
            field=models.CharField(max_length=50),
        ),
    ]
