# Generated by Django 4.2.2 on 2023-07-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0002_alter_cohorte1_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohorte1',
            name='CI',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
